[package]
name = "zen-browser"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core
tokio = { version = "1.45.1", features = ["full"] }
reqwest = { version = "0.12.20", features = ["json"] }
html5ever = "0.32.0"
cssparser = "0.35.0"
log = "0.4.27"
env_logger = "0.11.8"

# GUI (optional, choose one)
winit = "0.30.11"
iced = { version = "0.13.1", optional = true }
druid = { version = "0.8.3", optional = true }

# Rendering
raqote = "0.8.5"
font-kit = "0.14.3"
ab_glyph = "0.2.29"